name: "Validate Bitcart Plugins"

description: "Validate Bitcart plugins in a directory"

inputs:
  directory:
    description: "Directory containing plugins"
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: Validate plugins
      shell: bash
      env:
        DIRECTORY: ${{ inputs.directory }}
      run: |
        if [ -f "${DIRECTORY}/manifest.json" ]; then
          bitcart-cli plugin validate "${DIRECTORY}"
        else
          for dir in "${DIRECTORY}"/*/; do
            bitcart-cli plugin validate "$dir"
          done
        fi
