name: "Install bitcart-cli"

description: "Install the Bitcart CLI binary"

inputs:
  use-go:
    description: "Install via go install (requires Go on PATH)"
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Install bitcart-cli (go)
      if: inputs.use-go == 'true'
      shell: bash
      run: go install github.com/bitcart/bitcart-cli@latest

    - name: Install bitcart-cli (binary release)
      if: inputs.use-go != 'true'
      shell: bash
      run: |
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m)
        case "$ARCH" in
            arm64)   ARCH="aarch64" ;;   # macOS returns arm64, releases use aarch64
            armv7l)  ARCH="armv7" ;;     # Linux returns armv7l, releases use armv7
        esac
        sudo curl -L "https://github.com/bitcart/bitcart-cli/releases/latest/download/bitcart-cli-${OS}-${ARCH}" \
            -o /usr/local/bin/bitcart-cli
        sudo chmod +x /usr/local/bin/bitcart-cli
