name: "Login to Registries"

description: "Login to Docker Hub and GitHub Container Registry"

inputs:
  dockerhub-user:
    description: "Docker Hub username"
    required: true
  dockerhub-token:
    description: "Docker Hub token"
    required: true

runs:
  using: composite
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-user }}
        password: ${{ inputs.dockerhub-token }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
