name: "Setup Python"

description: "Set up Python with uv"

inputs:
  python-version:
    description: "Python version to install"
    required: false
    default: "3.12"

runs:
  using: composite
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "UV_PYTHON_PREFERENCE=only-managed" >> "$GITHUB_ENV"
        echo "PYTHON=${{ inputs.python-version }}" >> "$GITHUB_ENV"

    - name: Set up Python ${{ inputs.python-version }}
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ inputs.python-version }}
        enable-cache: true
        activate-environment: true
