name: "Upload Codecov Coverage"

description: "Upload coverage report to Codecov"

inputs:
  token:
    description: "Codecov upload token"
    required: true
  name:
    description: "Name for Codecov report"
    required: false
    default: ""
  flags:
    description: "Codecov flags"
    required: false
    default: "tests"
  env_vars:
    description: "Environment variables to include in Codecov report"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        token: ${{ inputs.token }}
        name: ${{ inputs.name }}
        flags: ${{ inputs.flags }}
        env_vars: ${{ inputs.env_vars }}
        files: test-results/coverage.xml
        disable_search: true

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/codecov-action@v5
      with:
        token: ${{ inputs.token }}
        report_type: test_results
        files: test-results/junit.xml
        disable_search: true
