name: "Upload Codecov Coverage"

description: "Upload coverage report to Codecov"

inputs:
  token:
    description: "Codecov upload token"
    required: true
  name:
    description: "Name for Codecov report"
    required: false
    default: ""
  flags:
    description: "Codecov flags"
    required: false
    default: "tests"
  env_vars:
    description: "Environment variables to include in Codecov report"
    required: false
    default: ""
  upload_coverage:
    description: "Whether to upload coverage report"
    required: false
    default: "true"
  test_results_files:
    description: "JUnit XML file paths to upload (supports globs)"
    required: false
    default: "test-results/junit.xml"

runs:
  using: composite
  steps:
    - name: Prepare coverage XML
      if: ${{ inputs.upload_coverage == 'true' }}
      shell: bash
      run: |
        coverage xml -o test-results/coverage.xml

    - name: Upload coverage
      if: ${{ inputs.upload_coverage == 'true' }}
      uses: codecov/codecov-action@v5
      with:
        token: ${{ inputs.token }}
        name: ${{ inputs.name }}
        flags: ${{ inputs.flags }}
        env_vars: ${{ inputs.env_vars }}
        files: test-results/coverage.xml
        disable_search: true

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/codecov-action@v5
      with:
        token: ${{ inputs.token }}
        name: ${{ inputs.name }}
        flags: ${{ inputs.flags }}
        env_vars: ${{ inputs.env_vars }}
        report_type: test_results
        files: ${{ inputs.test_results_files }}
        disable_search: true
