name: "Run in background"

description: "Run a command in the background and output its logs in the post step."

inputs:
  run:
    description: "Command to run in the background."
    required: true
  key:
    description: "Unique key to identify this background process (used for log file names and state)."
    required: false
    default: "POST"

runs:
  using: composite
  steps:
    - uses: bitcart/bitcart-actions/actions/with-post-step@master
      with:
        key: ${{ inputs.key }}
        main: |
          bash --noprofile --norc -eo pipefail -c '
            BGDIR="${RUNNER_TEMP}/run-in-background"
            mkdir -p "$BGDIR"

            (${{ inputs.run }}) > "$BGDIR/${{ inputs.key }}.out" 2> "$BGDIR/${{ inputs.key }}.err" &
            disown
          '
        post: |
          MATCHERS=()
          for f in "$RUNNER_TEMP"/*.json; do
            owner=$(jq -r '.problemMatcher[]?.owner // empty' "$f" 2>/dev/null)
            if [ -n "$owner" ]; then
              echo "::remove-matcher owner=${owner}::"
              MATCHERS+=("$f")
            fi
          done

          echo "Found ${#MATCHERS[@]} problem matchers"

          if [ -f "$BGDIR/${{ inputs.key }}.out" ]; then
            echo "::group::stdout"
            echo "::stop-commands::${TOKEN}"
            cat "$BGDIR/${{ inputs.key }}.out"
            echo "::${TOKEN}::"
            echo "::endgroup::"
          fi
          if [ -f "$BGDIR/${{ inputs.key }}.err" ]; then
            echo "::group::stderr"
            echo "::stop-commands::${TOKEN}"
            cat "$BGDIR/${{ inputs.key }}.err"
            echo "::${TOKEN}::"
            echo "::endgroup::"
          fi

          for f in "${MATCHERS[@]}"; do
            echo "::add-matcher::${f}"
          done
