name: Zizmor Audit

on:
  workflow_call:
    inputs:
      paths:
        description: "The paths to run the audit on"
        required: false
        type: string
        default: "."
      advanced-security:
        description: "Whether to enable advanced security features (github only)"
        required: false
        type: boolean
        default: true
      persona:
        description: "Zizmor persona (regular, pedantic, auditor)"
        required: false
        type: string
        default: "auditor"

permissions:
  contents: read

jobs:
  run:
    name: run
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write # needed for github advanced security

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@b1d7e1fb5de872772f31590499237e7cce841e8e # v0.5.3
        with:
          inputs: ${{ inputs.paths }}
          advanced-security: ${{ inputs.advanced-security }}
          persona: ${{ inputs.persona }}
