name: Zizmor Audit

on:
  workflow_call:
    inputs:
      paths:
        description: "The paths to run the audit on"
        type: string
        default: "."
      advanced-security:
        description: "Whether to enable advanced security features (github only)"
        type: boolean
        default: true
      persona:
        description: "Zizmor persona (regular, pedantic, auditor)"
        type: string
        default: "auditor"
      runs-on:
        description: "Runner label to run the job on"
        type: string
        default: "ubuntu-latest"

permissions:
  contents: read

jobs:
  run:
    name: run
    runs-on: ${{ inputs.runs-on }}

    permissions:
      contents: read
      security-events: write # needed for github advanced security

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2
        with:
          inputs: ${{ inputs.paths }}
          advanced-security: ${{ inputs.advanced-security }}
          persona: ${{ inputs.persona }}
