name: Zizmor Audit

on:
  workflow_call:
    inputs:
      paths:
        description: "The paths to run the audit on"
        type: string
        default: "."
      advanced-security:
        description: "Whether to enable advanced security features (github only)"
        type: boolean
        default: true
      persona:
        description: "Zizmor persona (regular, pedantic, auditor)"
        type: string
        default: "auditor"
      runs-on:
        description: "Runner label to run the job on"
        type: string
        default: "ubuntu-latest"

permissions:
  contents: read

jobs:
  run:
    name: run
    runs-on: ${{ inputs.runs-on }}

    permissions:
      contents: read
      security-events: write # needed for github advanced security

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@cc914d7f3750a2d13d75c7f184a1060aa0e9d482 # v0.6.4
        with:
          inputs: ${{ inputs.paths }}
          advanced-security: ${{ inputs.advanced-security }}
          persona: ${{ inputs.persona }}
